### ISSUE TITLE
Auto-update rendered files

### ISSUE THREAD

**Issue by samvv** [TypeForce/tsdoc#36]
It should be possible to auto-update files without the user requiring a manual `rm -rf docs/` before each invocation of the documenter. One thing I thought about is that a small JSON-file containing the hashes of all generated files could be saved in the output directory, which is checked when `tsdoc` is re-run. If the hash matches the old file, it is replaced. Otherwise, it is left as is and perhaps the user is prompted to replace it.

**Comment by BurtHarris** [comment]
As mentioned in the other project, that sounds a lot like gulp-changed and/or gulp-updated.

I'm not sure I understand about `rm -rf docs/` yet.   I noticed it the files created there and was thinking perhaps we should `.gitignore` the directory.

**Comment by samvv** [comment]
`.gitignore` should probably need updating; the only thing I thought of is that `docs/` can be used to document TSDoc itself. We can then link it to a GitHub Page. That's why I didn't add it to `.gitignore` just yet.

**Comment by samvv** [comment]
Closing this as `tsdoc` will integrate with something like `gulp` and it's up to the user's gulp configuration to address this. Might get re-opened in the future if we want to provide a more advanced stand-alone tool.
