### ISSUE TITLE
Use TypeScript transformers instead of custom visitor

### ISSUE THREAD

**Issue by samvv** [TypeForce/tsdoc#46]
It was nice auto-generating a generic visitor, but it won't do much as the code gets more complex. Instead, manually create a visitor that will keep a local state of useful information while it passes through the nodes. Its main objectives are categorising nodes and filtering as described in issue #32 .

**Comment by BurtHarris** [comment]
@samvv I'm not sure why we need to create a visitor.   Doesn't typescript already have this covered with their transformer-related classes?   I think we just implement a transform or two, and pass them in to the TypeScript APIs.

**Comment by samvv** [comment]
I've been looking into them and you're right, we can just re-use the ones of TypeScript. Changing the issue now.

**Comment by BurtHarris** [comment]
It seems to me like it would be good to write a lightweight prototype here, e.g. write a simple Transformer that inserts a '@returns <typeExpression> comment for every function that doesn't already have one. 

I'm not sure how that would interact with functions with overloaded definitions, but we don't need to handle that case at first.

Based on code inspection alone, I'm not convinced that the TypeScript issue claiming that [Cannot add or modify JSDoc with custom transformers](https://github.com/Microsoft/TypeScript/issues/15639) is right.   There doesn't seem to be anything special about those factory methods, if they are using public APIs to do their work I don't see why any changes to the TypeScript API should be needed to insert items into the parse tree, and use the existing `ts.emitFiles()` function to apply the transforms and invoke emitter functionality.

On the other hand, it seems that the TypeScript team has added extensibility hooks to the TypeScript LanguageService (see Microsoft/TypeScript#6508).   I'll dig a little further to this to see if it might make sense to do this in a LanguageService extension.

**Comment by samvv** [comment]
You've been doing your research! I haven't looked at the LanguageService yet, will take a look at it later this evening when I'm back home. And you're right, it might still be possible to generate synthetic JSDoc tags even without the use of TypeScript's built-in factory methods.

**Comment by samvv** [comment]
So I've been thinking more about it and I'm getting more and more convinced that we are trying to do two very different things: adding comments to TypeScript's parse tree and rendering HTML. I think it is better to create two separate repositories for these two separate things. In my eyes, `typedoc` seems a more apt name  for a HTML rendering tool while something like `tsannotate` could be used for something like an annotation tool. Even more I don't know if @BurtHarris agrees on this or not. I don't know what you think about the issue @BurtHarris, but I think it is better to create two separate repos or, even better, create a patch that integrates this functionality in TypeScript itself.

**Comment by samvv** [comment]
@BurtHarris I've been p

**Comment by BurtHarris** [comment]
@samvv I think its premature to create a whole new repository.  You are right they are two different approaches, but one or the other may run into roadblocks, and retaining a common repository of issues seems more important right now than separating code, which can be done with different branches in this repo.   How about we just create labels for tagging issues with one approach or the other?

**Comment by samvv** [comment]
@BurtHarris All right for me, though I suspect it will be a tough nut to crack.
