### ISSUE TITLE
gulp-jsdoc3 is complicating matters...

### ISSUE THREAD

**Issue by BurtHarris** [TypeForce/tsdoc#48]
I'm having some trouble with the `gulp-jsdoc3` plugin which I'd rather avoid than troubleshoot.   I'm planning on removing it from our dependencies.

**Comment by pgonzal** [comment]
@BurtHarris are you sure that you reported this issue to the right project?  I don't believe the `tsdoc` library is using `gulp-jsdoc3`.

**Comment by BurtHarris** [comment]
sorry, I've lost interest at this point, too much else in my life.
